### ISSUE TITLE
UI: map issues

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/pm#61] opened 2016-11-10 11:36 UTC
* The map is slow (main stats start page) -> need a speedup
  * switching between weeks in the map is slow  -> need a speedup
  * mouse focus gets "grabbed" by the map when there, this might be confusing
  * if there is no data for a default setting of a map (open recursive DNS), it should iterate over the other data sets and display _something_ at least (unless, that particular risk was chosen specifically before )

**Comment by rufuspollock** [comment] 2016-11-21 17:58
DUPLICATE of various issues in stats-new (let's keep issues there and if we have stuff here it must be a summary linking to specific issues there).

**Closed as completed by rufuspollock** 2016-11-21 17:58 UTC
Labels: duplicate, enhancement
