### ISSUE TITLE
Reference data sets [super]

### ISSUE THREAD

**Issue by aaronkaplan** [cybergreen-net/pm#2] opened 2016-08-10 17:16 UTC
# Needed
- [ ] IP2ASN datasets  - including historic data
- [x] Country2ASNs datasets  (See #1 ) - also historic ones if possible. Or keep a history of them
- [ ] Maxmind/GeoIP
- [x] Country ; population
- [x] Country ; number of announced IP addresses
- [x] Risk inventory (list of risks with url friendly identifier, type, description ...)

**Comment by rufuspollock** [comment] 2016-08-17 00:06
Existing datasets for e.g. population, GDP, country codes in core datasets project:

http://data.okfn.org/data/

Especially:

http://data.okfn.org/data/country-list
http://data.okfn.org/data/country-codes

Datasets are actually stored on github at https://github.com/datasets/ e.g. 

https://github.com/datasets/country-codes/

**Comment by aaronkaplan** [comment] 2016-08-17 00:24
> On 17 Aug 2016, at 02:06, Rufus Pollock notifications@github.com wrote:
> 
> Existing datasets for e.g. population, GDP, country codes in core datasets project:
> 
> http://data.okfn.org/data/
> 
> Especially:
> 
> http://data.okfn.org/data/country-list
> http://data.okfn.org/data/country-codes
> 
> Datasets are actually stored on github at https://github.com/datasets/ e.g.
> 
> https://github.com/datasets/country-codes/

How are they updated automatically?

In other words: do I need to care to keep them up to date from some authoritative source (such as ISO) or does someone else take care of that?
And for how long and under what guarantees?

**Comment by chorsley** [comment] 2016-08-17 02:10
I imagine we'll need to develop some periodic background process which does a fetch, validation, and commit to Git for each authoritative source we select. Maxmind already has this mechanism (https://github.com/maxmind/geoipupdate) but we'll need to design something more generic.

We will need to do some calculations on the data volumes this might generate for the reference dataset repo, but Git is relatively efficient with deltas and doing garbage collection.

The next thing to consider will be how we enable an enricher process to select and query the right historical reference dataset, but let's focus on the fetching and management for now.

**Comment by rufuspollock** [comment] 2016-08-18 09:44
@aaronkaplan 

> How are they updated automatically?

They are updated either manually or by automated scripting. Most of those only change quite slowly (e.g. annually).

> In other words: do I need to care to keep them up to date from some authoritative source (such as ISO) or does someone else take care of that? And for how long and under what guarantees?

No, you don't need to take care. If you wanted an SLA you could probably pay for one ;-) (I run that project).

@chorsley at the start here I'd suggest we keep it very KISS - that is do the simplest think possible which is a one-off scrape. We can automate all of this later once we know what we need to automate, how often etc etc. Otherwise you end up spending quite a lot of effort automating something that turns out not to be super important.

**Comment by rufuspollock** [comment] 2016-08-18 09:49
@aaronkaplan re reference datasets one thing i would recommend is that we adopt a one repo per dataset policy (at least roughly). E.g. ASNs would be one repo, GDP another.

**Comment by chorsley** [comment] 2016-08-18 13:42
@rgrp I was of a mind to keep them together in a single repo, or broken into use case (e.g. data platform enrichment / stats analysis). We'll probably always use these datasets together, so it would make deployment and management easier if you can pull everything from one place, or we can just download the raw file for a particular dataset if we want to isolate a single file and version. One issue might be ongoing size of the repo, depending on what we start putting in it.

Is there a particular scenario you had in mind where one repo per dataset might help?

**Comment by aaronkaplan** [comment] 2016-08-18 13:43
> On 18 Aug 2016, at 11:49, Rufus Pollock notifications@github.com wrote:
> 
> @aaronkaplan re reference datasets one thing i would recommend is that we adopt a one repo per dataset policy (at least roughly). E.g. ASNs would be one repo, GDP another.

Feel free to re-arrange please.

**Comment by aaronkaplan** [comment] 2016-08-18 13:44
> On 18 Aug 2016, at 15:42, Chris Horsley notifications@github.com wrote:
> 
> @rgrp I was of a mind to keep them together in a single repo, or broken into use case (e.g. data platform enrichment / stats analysis). We'll probably always use these datasets together, so it would make deployment and management easier if you can pull everything from one place, or we can just download the raw file for a particular dataset if we want to isolate a single file and version. One issue might be ongoing size of the repo, depending on what we start putting in it.

I tend to agree with Chris here, but... if you two guys decide that separate repos make more sense, then please feel free to re-arrange it.
okay?

**Comment by rufuspollock** [comment] 2016-08-22 06:46
@chorsley the one repo per dataset can be easier in that:
- Its one repo for one job. This is just cognitively a bit simpler and it makes it easier for contributors to dive in (esp in future)
- It avoids too much duplication. E.g. country codes may end up in every use case repo - you have the same code and data in multiple locations
- It makes the alignment with data packages a little bit simpler (but not required)

At the same time your point about needing items together makes sense.

I think this is something it may be worth chatting about briefly - perhaps on the call.

**Comment by kxyne** [comment] 2016-08-22 07:40
Best of both worlds is probably https://git-scm.com/book/en/v2/Git-Tools-Submodules if I understand you correctly.

**Comment by rufuspollock** [comment] 2016-08-22 08:18
@kxyne yes!

**Comment by rufuspollock** [comment] 2016-09-26 10:53
FIXED / DUPLICATE of other issues.

**Closed as completed by rufuspollock** 2016-09-26 10:53 UTC
Labels: enhancement, help wanted
